
        </div>
    </main>

    <footer class="footer text-center py-3 bg-light">
        <div class="container">
        <span class="text-muted">Faheem Khan Shaheen | @0056478 | Client Server Systems | 50249 | University of Salford</span>
        </div>
    </footer>
</body>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.bundle.min.js"></script>
</body>
</html>