<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">

    <title>Random Cafe Social Network | <?php echo $view->pageTitle; ?></title>

    <style>
        .navbar-expand-md {
            justify-content: space-between !important;
        }
    </style>
</head>
<body class="d-flex flex-column vh-100 vw-100 m-0" cz-shortcut-listen="true">
    <header class="shadow-sm bg-body rounded">
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-light bg-white px-5">
            <a class="navbar-brand" href="/faheem/CSC-Assessment/index.php"><img src="images/logo.jfif" width="150" height="50" alt="Random Cafe Social Network" /></a>
            <a class="navbar-brand" href="https://www.salford.ac.uk/" target="_blank"><img src="images/new_uos_logo.jpg" width="100" height="50" alt="University of Salford" /></a>
            <?php
                if (!isset($_SESSION["login"])) {
                    // Include the login-register.phtml template if the user is not logged in
                    require("login-register.phtml");
                }
                else {
                    // Show user's username and image, and logout button if the user is logged in
                    echo '<div class="d-flex align-items-center">
                        <span class="me-2 fw-bold fst-italic">@' . $_SESSION["login"] . '</span>
                        <img src="images/' . $user->getUserImgPath() . '" alt="mdo" width="40" height="40" class="rounded-circle me-2">
                        <form method="post" action="">
                            <input type="submit" name="logout_btn" value="Logout" class="btn btn-outline-danger">
                        </form>
                    </div>';
                }
            ?>
        </nav>
    </header>
        
    <!-- Begin page content -->
    <main class="flex-grow-1 pt-3 position-relative">
        <div class="container">